package com.nooz.nooz.activity.settings;

import android.app.ActionBar;
import android.app.Activity;
import android.os.Bundle;
import android.view.Menu;
import android.widget.FrameLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import com.nooz.nooz.R;

public class TextViewActivity extends Activity {
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		FrameLayout layout = (FrameLayout) this.getWindow().getDecorView().findViewById(android.R.id.content);
		ScrollView scrollingLayout = new ScrollView(this);
		layout.addView(scrollingLayout);
		TextView textView = new TextView(this);
		String preferenceKey = getIntent().getStringExtra("preferenceKey");
		if (getString(R.string.open_source_licenses).equals(preferenceKey)) {
			textView.setText("" + "## License for Google Maps Android API v2\n" + "## License for android-volley\n"
					+ "\n" + "Copyright 2005-2008, The Android Open Source Project\n" + "\n"
					+ "Licensed under the Apache License, Version 2.0 (the \"License\");\n"
					+ "you may not use this file except in compliance with the License.\n"
					+ "You may obtain a copy of the License at\n" + "\n"
					+ "   http://www.apache.org/licenses/LICENSE-2.0\n" + "\n"
					+ "Unless required by applicable law or agreed to in writing, software\n"
					+ "distributed under the License is distributed on an \"AS IS\" BASIS,\n"
					+ "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
					+ "See the License for the specific language governing permissions and\n"
					+ "limitations under the License.\n" + "\n" + "## License for cwac-camera\n" + "\n"
					+ "Copyright 2014 CommonsWare, LLC\n" + "\n"
					+ "Licensed under the Apache License, Version 2.0 (the \"License\");\n"
					+ "you may not use this file except in compliance with the License.\n"
					+ "You may obtain a copy of the License at\n" + "\n"
					+ "   http://www.apache.org/licenses/LICENSE-2.0\n" + "\n"
					+ "Unless required by applicable law or agreed to in writing, software\n"
					+ "distributed under the License is distributed on an \"AS IS\" BASIS,\n"
					+ "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
					+ "See the License for the specific language governing permissions and\n"
					+ "limitations under the License.\n" + "\n" + "## License for android-crop\n" + "\n"
					+ "Copyright 2014 SoundCloud\n" + "\n"
					+ "Licensed under the Apache License, Version 2.0 (the \"License\");\n"
					+ "you may not use this file except in compliance with the License.\n"
					+ "You may obtain a copy of the License at\n" + "\n"
					+ "   http://www.apache.org/licenses/LICENSE-2.0\n" + "\n"
					+ "Unless required by applicable law or agreed to in writing, software\n"
					+ "distributed under the License is distributed on an \"AS IS\" BASIS,\n"
					+ "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
					+ "See the License for the specific language governing permissions and\n"
					+ "limitations under the License.\n" + "\n" + "## Liceense for azure-mobile-services\n" + "\n"
					+ "Copyright 2014 Microsoft Corporation\n" + "\n"
					+ "Licensed under the Apache License, Version 2.0 (the \"License\");\n"
					+ "you may not use this file except in compliance with the License.\n"
					+ "You may obtain a copy of the License at\n" + "\n"
					+ "   http://www.apache.org/licenses/LICENSE-2.0\n" + "\n"
					+ "Unless required by applicable law or agreed to in writing, software\n"
					+ "distributed under the License is distributed on an \"AS IS\" BASIS,\n"
					+ "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
					+ "See the License for the specific language governing permissions and\n"
					+ "limitations under the License.\n" + "");
		} else if (getString(R.string.privacy_policy).equals(preferenceKey)) {
			textView.setText(""
					+ "Privacy Policy\n"
					+ " \n"
					+ "Effective date:  May 2014\n"
					+ " \n"
					+ "Welcome to Nooz (“Nooz”, “we”, “us” or “our”).  Nooz is a mobile app and website that delivers credible crowd sourced news content through a unique map-based interface.  \n"
					+ "\n"
					+ "Our Privacy Policy describes how we and the businesses we work with collect, use, share and protect information connecting to our mobile and website Nooz services. \n"
					+ " \n"
					+ "By using Nooz you understand and agree that we are providing a platform for you to publically post audio and visual content as well as comments.  This means that other users may search for, see and share the content you make publically available through our service, consistent with the terms and conditions of this Privacy Policy and our Terms of Use.\n"
					+ " \n"
					+ "Our policy applies to all users who access the service (“Users”).\n"
					+ " \n"
					+ "1. INFORMATION WE COLLECT\n"
					+ "\n"
					+ "Nooz collects the following information \n"
					+ "\n"
					+ "Information you provide us directly:\n"
					+ "Your username, password and email address when you register for an Nooz account.\n"
					+ "Profile Information provided for your user profile (e.g.  first and last name, picture).  This information lets Nooz help you or others be “found” on Nooz.\n"
					+ "User content (e.g.  photos, comments and other materials) that you post to service\n"
					+ "Communications between you and Nooz.  For instance, service-related emails (e.g.  account verification, service updates, technical and security notices).  \n"
					+ "\n"
					+ "Analytics information:  \n"
					+ "Nooz uses analytics sent by your device to measure traffic and usage trends to assist us in improving our service.   \n"
					+ "\n"
					+ "Cookies and similar technologies:  \n"
					+ "When you visit Nooz we may use cookies and local storage to collect information regarding how you use our service to better provide features to you.  \n"
					+ "Nooz may explore the idea of having local advertisers serve ads to your device, which may use cookies as well.\n"
					+ "\n"
					+ "Log file information:\n"
					+ "Log file information is recorded by your browser each time you request access to our app or web page.  \n"
					+ "When using Nooz our servers record web requests, browser type, Internet Protocol address, referring/exit pages, pages viewed, landing pages, domain names, number of clicks and your interactions with links on our service and other similar information. \n"
					+ "\n"
					+ "Device identifiers:\n"
					+ "When using a mobile device to access Nooz we may collect, monitor and store one or more device identifiers.  Device identifiers are data structures stored within your mobile device’s hardware, operating system or software which identifies your device for our service.  \n"
					+ "A device identifier sends information to us about how you use Nooz and helps us provide you with personalized content.  Some aspects of the app and website will not function properly if device identifiers are impaired or disabled.  \n"
					+ "\n"
					+ "Metadata:\n"
					+ "Users may add metadata to their user content by selecting a topic and adding a headline, keyword or text caption to their stories.  All users’ “breaking news” is location verified through GPS  before content is shared and made publically searchable by others.  \n"
					+ " \n"
					+ "\n"
					+ "\n"
					+ "2.  HOW WE USE YOUR INFORMATION \n"
					+ "\n"
					+ " Nooz may use the information we are given to:\n"
					+ "improve and monitor the effectiveness of our service\n"
					+ "quickly diagnose technology issues\n"
					+ "remember your information so you will not have to log-in during your next visit\n"
					+ "(anonymously) monitor audience size and usage patterns \n"
					+ "provide personalized content and information, which may include various forms of marketing\n"
					+ "\n"
					+ "\n"
					+ "\n"
					+ "3.  SHARING OF YOUR INFORMATION \n"
					+ "\n"
					+ "Nooz will not sell your information to third parties without your consent.  \n"
					+ "\n"
					+ "Third parties with whom we may share your information:\n"
					+ "\n"
					+ "We may share device identifiers, location data, cookies, log files in a reasonably confidential way with the  third party organizations that help us provide the service to you.    \n"
					+ "\n"
					+ "Third parties with whom you may share your User Content:  \n"
					+ "\n"
					+ "Content that you voluntarily disclose to the public can be seen by others.  Please exercise caution before disclosing information via these public venues.  \n"
					+ "Content posted to the service and subsequently removed remains viewable in cached and archived pages of the service. \n"
					+ "\n"
					+ "What happens in the event of change of control:\n"
					+ "\n"
					+ "If we sell or transfer a portion of Nooz or our assets to another organization (e.g.  a merger, acquisition, liquidation, dissolution, bankruptcy), your information and user content may be among the items sold or transferred. You will continue to own your user content and the buyer or transferee must honor any commitment we have made in this privacy policy.\n"
					+ "\n"
					+ "Responding to legal requests and preventing harm:\n"
					+ "\n"
					+ "In response to a legal request (e.g.  search warrant, court order, subpoena or governmental investigation) Nooz reserves the right to access, preserve and share your information if we feel the law, or in good-faith believe such action is necessary to comply with state and federal laws.  This may include responding to legal requests made outside the borders of the United States if we feel it affects other users in that jurisdiction.    \n"
					+ " \n"
					+ "\n"
					+ "\n"
					+ "4.  HOW WE STORE YOUR INFORMATION\n"
					+ "\n"
					+ "Storage and Processing:  \n"
					+ "\n"
					+ "Your collected Nooz information may be stored and processed within the United States.\n"
					+ "By registering for and using our service you accept the transfer of information within the United States.\n"
					+ "Our service makes an effort to protect all information collected by requesting a unique password from users before granting them access to their account.  However our service cannot guarantee the security of all transmitted information. \n"
					+ "Please do your part to help.  You are responsible for maintaining the secrecy of your password and account information, at all times.  Your privacy measures may be impacted by changes within other social media services you choose to connect to Nooz.  We are not responsible for the privacy, security and performance of any other organizations.  \n"
					+ "\n"
					+ "\n"
					+ "\n"
					+ "\n"
					+ "\n"
					+ "5.  YOUR CHOICES ABOUT YOUR INFORMATION\n"
					+ "\n"
					+ "Your account information and profile/privacy settings:  \n"
					+ "\n"
					+ "You may update your account at anytime by logging in and changing your personal profile settings.\n"
					+ "You may unsubscribe from email communications by clicking the “unsubscribe link” within Nooz emails.  However you may not opt out of our service-related emails (e.g.  account verification, changes and service updates and security notices).\n"
					+ "We want to communicate with you only if you want to hear from us.\n"
					+ "\n"
					+ "How long we keep your user content:\n"
					+ "\n"
					+ "Following deactivation or termination of your account, Nooz and its service providers may retain information and user content temporarily for backup, archival or audit purposes.  \n"
					+ "\n"
					+ "6.  OUR POLICY TOWARDS CHILDREN\n"
					+ "\n"
					+ "Nooz does not knowingly collect information from users under the age of 13 or knowingly allow such persons to register for the service.  \n"
					+ "\n"
					+ "7.  OTHER WEB SITES AND SERVICES\n"
					+ "\n"
					+ "Nooz is not liable for the practices of other websites or services linked to our service.  When linking our service to another website or service our Privacy Policy does not apply and all linked content is subject to that third party’s respective rules and policies.  Additionally, we are not responsible nor do we have control of third parties that you authorize to access your User Content.  Please exercise caution and understand that using a third party website or service is done at your own risk, Nooz is no way responsible.\n"
					+ "\n"
					+ "8.  HOW TO CONTACT US\n"
					+ "\n"
					+ "If you have questions regarding this Privacy Policy or our service feel free to contact Nooz directly.  You may find this information in the About Us channel located in our app or website.  \n"
					+ "\n"
					+ "9.  CHANGES TO OUR PRIVACY POLICY \n"
					+ "\n"
					+ "Nooz may amend this Privacy Policy occasionally, so please review it periodically.  We may provide additional forms, modifications or updates as appropriate under the circumstances.  Any future changes we may make to our privacy policy will be posted on this page and notified to you by e-mail.  Please note your continued use of Nooz’s services signifies your acceptance of our revised Privacy Policy.   \n"
					+ "");
		} else if (getString(R.string.terms_of_use).equals(preferenceKey)) {
			textView.setText(""
					+ "Terms of Use\n"
					+ "\n"
					+ "These Terms of Use are effective on May 2014\n"
					+ "______________________________________________________________________________\n"
					+ "\n"
					+ "By accessing or using the Nooz application or the Nooz website provided by Nooz you agree to be bound by these terms of use.  The service is owned and controlled by Nooz (LLC?).  These terms of use impact your legal rights and obligations and if you do not agree to be bound by these Terms of Use please do not access or use the Nooz service.  \n"
					+ "\n"
					+ "Occasionally we may offer a new component that has its own terms and conditions that apply in addition to these Terms of Use. \n"
					+ "\n"
					+ "ARBITRATION NOTICE:  YOU AGREE THAT DISPUTES INVOLVING YOU AND NOOZ WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS WIDE ARBITRATION.\n"
					+ "\n"
					+ "Basic Terms\n"
					+ "\n"
					+ "You must be at least 13 years old to use the service\n"
					+ "You may not post unlawful, nude, pornographic or sexually suggestive photos via the service.\n"
					+ "You are liable for any activity that occurs within your account and you agree not to sell or transfer  your account, username or account rights.  \n"
					+ "");
		}
		scrollingLayout.addView(textView);
	}

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		ActionBar actionBar = getActionBar();
		actionBar.setTitle(getIntent().getStringExtra("preferenceKey"));
		return super.onCreateOptionsMenu(menu);
	}
}
